apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3zyz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-3zyz@sha256:e9da0f0fd4e21eb18f06ca96827c101931ec6f5d4903d4c44d0ee6fd538937ec
        name: my-nodejs
        resources: {}
status: {}
